apiVersion: v1
kind: PersistentVolume
metadata:
  name: request-db-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/request-db-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: request-db-pvc
  labels:
    app: postgres
    tier: database
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-db-deployment
  labels:
    app: request-db-deployment
    tier: database
spec:
  selector:
    matchLabels:
      app: request-db-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: request-db-deployment
        tier: database
    spec:
      containers:
        - name: request-db
          image: postgres
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5437
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_REQUEST
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_REQUEST
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: request-db-data
      volumes:
        - name: request-db-data
          persistentVolumeClaim:
            claimName: request-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: request-db-service
  labels:
    app: request-db-service
    tier: database
spec:
  ports:
    - port: 5437
      targetPort: 5437
      protocol: TCP
  selector:
    app: request-db-deployment
    tier: database
  type: LoadBalancer